//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFESSION()
        {
            this.GROUPS = new HashSet<GROUPS>();
        }
    
        public string PROFESSION1 { get; set; }
        public string FACULTY { get; set; }
        public string PROFESSION_NAME { get; set; }
        public string QUALIFICATION { get; set; }
    
        public virtual FACULTY FACULTY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS> GROUPS { get; set; }
    }
}
